DOCSP-40790: Write operations landing page
mongodb/docs-cpp pull request #38
Opened 2024-07-12 17:42 UTC by norareidy

# Pull Request Info

[PR Reviewing Guidelines](https://github.com/mongodb/docs-java/blob/master/REVIEWING.md)

JIRA - https://jira.mongodb.org/browse/DOCSP-40790
Staging - <https://docs-mongodbcom-staging.corp.mongodb.com/drivers/docsworker-xlarge/NNNNN/>

## Self-Review Checklist

- [ ] Is this free of any warnings or errors in the RST?
- [ ] Did you run a spell-check?
- [ ] Did you run a grammar-check?
- [ ] Are all the links working?
- [ ] Are the [facets and meta keywords](https://wiki.corp.mongodb.com/display/DE/Docs+Taxonomy) accurate?

2024-07-12 18:32 UTC, norareidy commented on source/write.txt
> +:ref:`Bulk Write <cpp-bulk-write>` guide.
Note to reviewer: link will be broken until #37 is merged

2024-07-16 14:56 UTC, rustagir requested changes
Main feedback is to add intro sentences!

2024-07-16 14:56 UTC, rustagir commented on source/write.txt
> +   :description: Learn how to use the {+driver-short+} to write data to MongoDB.
S: the source constant might not get parsed here
```suggestion
   :description: Learn how to use the C++ Driver to write data to MongoDB.
```

2024-07-16 14:56 UTC, rustagir commented on source/write.txt
> +
S: I think it's good practice to always introduce code examples. See my PR for kotlin sync for intros you can copy over https://github.com/mongodb/docs-kotlin-sync/pull/5
Applies to all sections

2024-07-16 14:56 UTC, rustagir commented on source/includes/usage-examples/write-code-examples.cpp
> +        auto query_filter = make_document(kvp("<field to match>", <value to match>));
S: for the sake of the syntax highlighting,  make the second param a string (applies to all)
```suggestion
        auto query_filter = make_document(kvp("<field to match>", "<value to match>"));
```

2024-07-16 15:58 UTC, rustagir approved these changes
looks great! thanks for making changes to the read page as well.

2024-07-17 17:24 UTC, kevinAlbs approved these changes

2024-07-17 18:09 UTC, merged