DOCSP-45311: Remove deprecated utf8 types
mongodb/docs-cpp pull request #78
Opened 2024-11-21 15:13 UTC by norareidy

# Pull Request Info

[PR Reviewing Guidelines](https://github.com/mongodb/docs-java/blob/master/REVIEWING.md)

JIRA - https://jira.mongodb.org/browse/DOCSP-45311
Staging - <https://docs-mongodbcom-staging.corp.mongodb.com/drivers/docsworker-xlarge/NNNNN/>

## Self-Review Checklist

- [ ] Is this free of any warnings or errors in the RST?
- [ ] Did you run a spell-check?
- [ ] Did you run a grammar-check?
- [ ] Are all the links working?
- [ ] Are the [facets and meta keywords](https://wiki.corp.mongodb.com/display/DE/Docs+Taxonomy) accurate?

2024-11-21 15:27 UTC, rustagir approved these changes
lgtm with some qs

2024-11-21 15:27 UTC, rustagir commented on source/upgrade.txt
> +    and ``bsoncxx::v_noabi::types::bson_value::view`` classes. Instead, use ``get_string``.
Q: is this a type or a method?

2024-11-21 15:27 UTC, rustagir commented on source/whats-new.txt
> +   - Removes the following deprecated ``utf8`` types that have ``string`` equivalents:
S: you could consider removing the full list from here and just linking to the upgrade guide for specific details and keep the list there?

2024-11-21 15:46 UTC, norareidy commented on source/upgrade.txt
> +    and ``bsoncxx::v_noabi::types::bson_value::view`` classes. Instead, use ``get_string``.
That one's a method! fixed

2024-11-22 15:30 UTC, eramongodb requested changes

2024-11-22 15:30 UTC, eramongodb commented on source/upgrade.txt
> +    and ``bsoncxx::v_noabi::types::bson_value::view`` classes. Instead, use ``get_string()``.
This is also an ABI breaking change. Suggest adding the following entry below:

```
- Removes deprecated ``utf8`` functions that have ``string`` equivalents. For context, see the <reference to ABI breaking changes> section.
```

2024-11-22 15:30 UTC, eramongodb commented on source/upgrade.txt
> +- Removes the following deprecated ``utf8`` types and methods that have ``string`` equivalents:
```suggestion
- Removes the following deprecated ``utf8`` types and functions that have ``string`` equivalents:
```
"Method" is not a well-defined term in C++.

2024-11-22 19:21 UTC, eramongodb approved these changes
One feedback remaining; otherwise, LGTM.

2024-11-22 19:21 UTC, eramongodb commented on source/upgrade.txt
> +- Removes deprecated ``utf8`` types and functions that have ``string`` equivalents.
```suggestion
- Removes deprecated ``utf8`` functions that have ``string`` equivalents.
```
Types are not part of the ABI. Only variables and functions are part of the ABI.

2024-11-22 20:27 UTC, merged