DOCSP-43248-upgrade-catch2-library
mongodb/docs-cpp pull request #90
Opened 2024-12-04 19:07 UTC by gmiller-mdb

# Pull Request Info

[PR Reviewing Guidelines](https://github.com/mongodb/docs-java/blob/master/REVIEWING.md)

JIRA - <https://jira.mongodb.org/browse/DOCSP-43248>
Staging - <https://docs-mongodbcom-staging.corp.mongodb.com/drivers/docsworker-xlarge/NNNNN/>

## Self-Review Checklist

- [ ] Is this free of any warnings or errors in the RST?
- [ ] Did you run a spell-check?
- [ ] Did you run a grammar-check?
- [ ] Are all the links working?
- [ ] Are the [facets and meta keywords](https://wiki.corp.mongodb.com/display/DE/Docs+Taxonomy) accurate?

2024-12-04 21:03 UTC, norareidy requested changes
Nice work! Left a few comments

2024-12-04 21:03 UTC, norareidy commented on source/upgrade.txt
> +  by disabling tests with ``ENABLE_TESTS=OFF{`` during CMake configuration.
S: remove {
```suggestion
  by disabling tests with ``ENABLE_TESTS=OFF`` during CMake configuration.
```

2024-12-04 21:03 UTC, norareidy commented on source/upgrade.txt
> +- If the ``ENABLE_TESTS`` variable is set to ``ON`` while building tests in CMake,
I: Since this change involves configuration options, I'd move this bullet to the "Build System Breaking Changes in v3.11" section

2024-12-05 18:46 UTC, norareidy approved these changes
lgtm!

2024-12-05 20:34 UTC, kevinAlbs approved these changes
LGTM with suggested rewording.

2024-12-05 20:34 UTC, kevinAlbs commented on source/upgrade.txt
> +  the driver to use C++14 or later. You can opt out of the C++14 requirement
```suggestion
- If the ``ENABLE_TESTS`` configuration option is set to ``ON``, C++14 or later is required. You can opt out of the C++14 requirement
```

Suggest removing "you must configure". Some compilers enable C++14 by default and do not require explicit configuration. [Example](https://clang.llvm.org/cxx_status.html#:~:text=By%20default%2C%20Clang%2016%20or,in%20Clang%204%20and%20earlier):

>  By default, Clang 16 or later builds C++ code according to the C++17 standard.

2024-12-05 21:00 UTC, merged